# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEntry',
            fields=[
                ('international_designator', models.CharField(max_length=11, unique=True)),
                ('norad_catalog_number', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=255)),
                ('has_payload', models.BooleanField(default=False)),
                ('launch_date', models.DateTimeField()),
                ('decay_date', models.DateTimeField()),
                ('orbital_period', models.PositiveSmallIntegerField()),
                ('inclination', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apogee', models.PositiveIntegerField()),
                ('perigee', models.PositiveIntegerField()),
                ('radar_cross_section', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchSite',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalStatus',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrbitalStatus',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=70)),
                ('second_line', models.CharField(max_length=70)),
                ('international_designator_year', models.CharField(max_length=2)),
                ('international_designator_number', models.CharField(max_length=3)),
                ('international_designator_piece', models.CharField(max_length=3)),
                ('epoch_year', models.CharField(max_length=2)),
                ('epoch_day', models.DecimalField(decimal_places=8, max_digits=11)),
                ('first_derivative_mean_motion', models.DecimalField(decimal_places=8, max_digits=9)),
                ('second_derivative_mean_motion', models.DecimalField(decimal_places=8, max_digits=9)),
                ('drag', models.DecimalField(decimal_places=9, max_digits=10)),
                ('set_number', models.PositiveIntegerField()),
                ('first_checksum', models.PositiveSmallIntegerField()),
                ('inclination', models.DecimalField(decimal_places=4, max_digits=7)),
                ('ascending_node', models.DecimalField(decimal_places=4, max_digits=7)),
                ('eccentricity', models.DecimalField(decimal_places=7, max_digits=8)),
                ('perigee_argument', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mean_anomaly', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mean_motion', models.DecimalField(decimal_places=8, max_digits=10)),
                ('revolution_number', models.PositiveIntegerField()),
                ('second_checksum', models.PositiveSmallIntegerField()),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.OperationalStatus')),
                ('satellite_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CatalogEntry')),
            ],
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='launch_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.LaunchSite'),
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='operational_status_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.OperationalStatus'),
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='orbital_status_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.OrbitalStatus'),
        ),
        migrations.AddField(
            model_name='catalogentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Source'),
        ),
    ]
