# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogentry',
            options={'verbose_name_plural': 'Catalog entries'},
        ),
        migrations.AlterModelOptions(
            name='operationalstatus',
            options={'verbose_name_plural': 'Operational statuses'},
        ),
        migrations.AlterModelOptions(
            name='orbitalstatus',
            options={'verbose_name_plural': 'Orbital statuses'},
        ),
        migrations.AlterModelOptions(
            name='tle',
            options={'verbose_name': 'Two Line Element', 'verbose_name_plural': 'Two Line Elements'},
        ),
    ]
