# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20161109_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='tle',
            name='third_line',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='tle',
            name='first_line',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='tle',
            name='second_line',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
