# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-02 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_tle_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogentry',
            name='norad_catalog_number',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='orbital_period',
            field=models.PositiveIntegerField(),
        ),
    ]
