# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-09 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170502_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogentry',
            old_name='operational_status_code',
            new_name='operational_status',
        ),
        migrations.RenameField(
            model_name='catalogentry',
            old_name='orbital_status_code',
            new_name='orbital_status',
        ),
    ]
