# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-22 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170509_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogentry',
            name='launch_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
         migrations.AlterField(
            model_name='catalogentry',
            name='apogee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='orbital_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='perigee',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='inclination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='radar_cross_section',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='inclination',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='catalogentry',
            name='orbital_period',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
