# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CAT', 'Catalog'), ('TLE', 'Two Line Elements')], default='CAT', max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('last_time_checked', models.DateTimeField()),
            ],
        ),
    ]
