# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='system_name',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
